// Server-rendered HTML for the dashboard.
const esc = (s) => String(s ?? '').replace(/[&<>"']/g, (c) => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' }[c]));
const CSS = `
@import url('https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600;700;800&display=swap');
:root{--bg:#0b0f14;--panel:rgba(255,255,255,.035);--panel2:rgba(255,255,255,.06);--line:rgba(255,255,255,.08);--line2:rgba(255,255,255,.14);--fg:#eef2f6;--muted:#8a94a6;--accent:#9b6bff;--accent2:#5865f2;--green:#3ddc84;--red:#ff5c6c;--yellow:#ffc857;--purple:#b48cff;--r:14px;--shadow:0 10px 30px rgba(0,0,0,.35)}
*{box-sizing:border-box}html{scroll-behavior:smooth}
body{margin:0;background:var(--bg);color:var(--fg);font:15px/1.55 Inter,system-ui,-apple-system,Segoe UI,Roboto,sans-serif;-webkit-font-smoothing:antialiased;min-height:100vh;background-image:radial-gradient(900px 500px at -10% -10%,rgba(155,107,255,.16),transparent 60%),radial-gradient(700px 400px at 110% 10%,rgba(109,140,255,.16),transparent 60%),radial-gradient(600px 400px at 50% 120%,rgba(180,140,255,.08),transparent 60%);background-attachment:fixed}
a{color:#8fd8ff;text-decoration:none}a:hover{text-decoration:underline}
::selection{background:rgba(155,107,255,.35)}
.top{display:flex;align-items:center;gap:14px;padding:12px 20px;background:rgba(11,15,20,.7);backdrop-filter:blur(14px);-webkit-backdrop-filter:blur(14px);border-bottom:1px solid var(--line);position:sticky;top:0;z-index:20}
.top .brand{font-weight:800;font-size:17px;color:var(--fg);letter-spacing:-.2px;display:flex;align-items:center;gap:8px}.top .brand:hover{text-decoration:none}
.top .sp{flex:1}.top img{width:30px;height:30px;border-radius:50%;border:2px solid var(--line2)}
.top .user{display:flex;align-items:center;gap:10px;color:var(--muted);font-size:14px;background:var(--panel);border:1px solid var(--line);padding:4px 12px 4px 4px;border-radius:999px}.top .user a{color:var(--muted)}.top .user a:hover{color:var(--fg)}
.wrap{display:flex;min-height:calc(100vh - 57px)}
.side{width:236px;padding:16px 12px;flex-shrink:0;position:sticky;top:57px;height:calc(100vh - 57px);overflow:auto}
.side a{display:flex;align-items:center;gap:10px;padding:10px 12px;border-radius:10px;color:var(--muted);margin-bottom:3px;font-weight:500;font-size:14.5px;transition:background .15s,color .15s,transform .15s}
.side a:hover{background:var(--panel2);color:var(--fg);text-decoration:none;transform:translateX(2px)}
.side a.on{background:linear-gradient(135deg,rgba(155,107,255,.28),rgba(109,140,255,.2));color:#fff;box-shadow:inset 0 0 0 1px rgba(155,107,255,.45)}
.side .g{padding:6px 12px 14px;border-bottom:1px solid var(--line);margin-bottom:10px;font-size:13px;color:var(--muted)}.side .g b{display:block;color:var(--fg);font-size:14.5px;margin-bottom:2px}.side .g img{width:22px;height:22px;border-radius:7px;vertical-align:middle;margin-right:6px}
main{flex:1;padding:28px 32px 60px;max-width:1120px;min-width:0}
h1{font-size:26px;margin:0 0 4px;font-weight:800;letter-spacing:-.4px}h2{font-size:15px;margin:26px 0 10px;font-weight:700;text-transform:uppercase;letter-spacing:.6px;color:var(--muted)}h3{margin:0 0 8px;font-size:16px}.sub{color:var(--muted);margin:0 0 22px;font-size:14.5px}
.card{background:var(--panel);border:1px solid var(--line);border-radius:var(--r);padding:20px;margin-bottom:16px;backdrop-filter:blur(6px);box-shadow:var(--shadow);transition:border-color .15s}.card:hover{border-color:var(--line2)}
.grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(170px,1fr));gap:14px}
.stat{background:var(--panel);border:1px solid var(--line);border-radius:var(--r);padding:18px 18px 14px;position:relative;overflow:hidden}.stat:before{content:'';position:absolute;inset:0 0 auto 0;height:3px;background:linear-gradient(90deg,var(--accent),var(--accent2),var(--purple))}
.stat b{display:block;font-size:30px;font-weight:800;letter-spacing:-.6px;background:linear-gradient(135deg,#fff,#d9ccff);-webkit-background-clip:text;background-clip:text;color:transparent}.stat span{color:var(--muted);font-size:12.5px;font-weight:500;text-transform:uppercase;letter-spacing:.5px}
label{display:block;margin:14px 0 6px;color:var(--muted);font-size:12px;font-weight:600;text-transform:uppercase;letter-spacing:.5px}
input[type=text],input[type=number],input[type=url],select,textarea{width:100%;background:rgba(0,0,0,.35);color:var(--fg);border:1px solid var(--line2);border-radius:10px;padding:10px 12px;font:inherit;transition:border-color .15s,box-shadow .15s;outline:none}
input:focus,select:focus,textarea:focus{border-color:var(--accent);box-shadow:0 0 0 3px rgba(155,107,255,.22)}
select{appearance:none;-webkit-appearance:none;background-image:url("data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' width='12' height='8'%3E%3Cpath d='M1 1l5 5 5-5' stroke='%238a94a6' stroke-width='2' fill='none'/%3E%3C/svg%3E");background-repeat:no-repeat;background-position:right 12px center;padding-right:32px}
select[multiple]{background-image:none;min-height:140px;padding:6px}select[multiple] option{padding:6px 8px;border-radius:6px}select[multiple] option:checked{background:linear-gradient(0deg,var(--accent),var(--accent));color:#fff}
textarea{min-height:90px;resize:vertical}
.row{display:grid;grid-template-columns:1fr 1fr;gap:16px}.row3{display:grid;grid-template-columns:1fr 1fr 1fr;gap:16px}
.tog{display:flex;align-items:center;gap:14px;padding:12px 0;border-bottom:1px solid var(--line)}.tog:last-child{border:0}.tog small{color:var(--muted);display:block;font-size:13px;font-weight:400}
.tog input[type=checkbox]{appearance:none;-webkit-appearance:none;width:44px;height:26px;border-radius:999px;background:rgba(255,255,255,.12);border:1px solid var(--line2);position:relative;cursor:pointer;flex-shrink:0;transition:background .2s,border-color .2s;margin:0}
.tog input[type=checkbox]:before{content:'';position:absolute;top:3px;left:3px;width:18px;height:18px;border-radius:50%;background:#fff;transition:transform .2s;box-shadow:0 1px 3px rgba(0,0,0,.4)}
.tog input[type=checkbox]:checked{background:linear-gradient(135deg,var(--accent),var(--accent2));border-color:transparent}.tog input[type=checkbox]:checked:before{transform:translateX(18px)}
button,.btn{background:linear-gradient(135deg,var(--accent),var(--accent2));color:#fff;border:0;border-radius:10px;padding:10px 18px;font:inherit;font-weight:700;cursor:pointer;display:inline-block;transition:transform .12s,box-shadow .15s,filter .15s;box-shadow:0 6px 18px rgba(155,107,255,.25)}
button:hover,.btn:hover{transform:translateY(-1px);filter:brightness(1.08);text-decoration:none}button:active{transform:translateY(0)}
button.sec,.btn.sec{background:var(--panel2);border:1px solid var(--line2);box-shadow:none;color:var(--fg)}button.danger,.btn.danger{background:linear-gradient(135deg,#ff5c6c,#ff3d7f);box-shadow:0 6px 18px rgba(255,92,108,.25);color:#fff}button.ok{background:linear-gradient(135deg,#3ddc84,#22c1a3)}
button.sm,.btn.sm{padding:6px 11px;font-size:13px;border-radius:8px}
.ok{background:rgba(61,220,132,.1);border:1px solid rgba(61,220,132,.4);color:#9be0b0;padding:12px 16px;border-radius:12px;margin-bottom:16px;font-weight:500}
.err{background:rgba(255,92,108,.1);border:1px solid rgba(255,92,108,.45);padding:12px 16px;border-radius:12px;margin-bottom:16px;font-weight:500}
table{width:100%;border-collapse:separate;border-spacing:0}th,td{padding:10px 12px;border-bottom:1px solid var(--line);text-align:left;font-size:14px;vertical-align:middle}th{color:var(--muted);font-weight:600;font-size:11.5px;text-transform:uppercase;letter-spacing:.5px}
tr:last-child td{border-bottom:0}tbody tr:hover td{background:rgba(255,255,255,.025)}
.tag{display:inline-block;padding:3px 10px;border-radius:999px;font-size:12px;font-weight:600;background:var(--panel2);border:1px solid var(--line);white-space:nowrap}
.tag.interview,.tag.open{background:rgba(180,140,255,.15);color:#d2b3ff;border-color:rgba(180,140,255,.35)}.chart{width:100%;height:auto;display:block}.chart text{font:11px Inter,sans-serif;fill:var(--muted)}.chart .bar:hover{filter:brightness(1.25)}.leg{display:flex;gap:14px;flex-wrap:wrap;font-size:13px;color:var(--muted);margin-top:8px}.leg i{display:inline-block;width:10px;height:10px;border-radius:3px;margin-right:5px;vertical-align:middle}
.tag.active{background:rgba(61,220,132,.15);color:#8fe0ad;border-color:rgba(61,220,132,.35)}.tag.loa{background:rgba(180,140,255,.15);color:#d2b3ff;border-color:rgba(180,140,255,.35)}.tag.resigned{color:var(--muted)}.tag.pending{background:rgba(109,140,255,.15);color:#b8c6ff;border-color:rgba(109,140,255,.35)}.tag.accepted,.tag.approved,.tag.verified{background:rgba(61,220,132,.15);color:#8fe0ad;border-color:rgba(61,220,132,.35)}.tag.denied{background:rgba(255,92,108,.15);color:#ff9aa5;border-color:rgba(255,92,108,.35)}.tag.strike{background:rgba(255,200,87,.15);color:#ffd27a;border-color:rgba(255,200,87,.35)}
.inline{display:inline}.inline button{margin-left:4px}.actions{display:flex;gap:6px;flex-wrap:wrap;align-items:center}
.gl{display:grid;grid-template-columns:repeat(auto-fill,minmax(280px,1fr));gap:14px}.gl a{display:flex;align-items:center;gap:14px;background:var(--panel);border:1px solid var(--line);border-radius:var(--r);padding:16px;color:var(--fg);transition:transform .15s,border-color .15s,box-shadow .15s}.gl a:hover{border-color:var(--accent);text-decoration:none;transform:translateY(-2px);box-shadow:var(--shadow)}.gl img,.gl .ph{width:48px;height:48px;border-radius:14px;background:linear-gradient(135deg,var(--accent),var(--accent2));display:flex;align-items:center;justify-content:center;font-weight:800;font-size:18px;color:#fff;flex-shrink:0}.gl small{display:block;color:var(--muted)}
.center{max-width:560px;margin:80px auto;text-align:center;padding:0 16px}.center img{width:104px;height:104px;border-radius:28px;margin-bottom:16px;box-shadow:0 20px 50px rgba(155,107,255,.3)}
.hero{display:flex;flex-direction:column;align-items:center;gap:10px}.hero h1{font-size:34px}.hero .btn{padding:14px 28px;font-size:16px;border-radius:12px;margin-top:8px}
.feat{display:grid;grid-template-columns:repeat(auto-fit,minmax(150px,1fr));gap:10px;margin-top:34px;text-align:left}.feat div{background:var(--panel);border:1px solid var(--line);border-radius:12px;padding:12px 14px;font-size:13.5px;color:var(--muted)}.feat b{display:block;color:var(--fg);font-size:14px;margin-bottom:2px}
code{background:rgba(0,0,0,.35);border:1px solid var(--line);padding:2px 7px;border-radius:6px;font-size:13px}
.dept{border:1px solid var(--line);border-radius:12px;padding:14px 16px;margin-bottom:14px;background:rgba(0,0,0,.15)}.dept h3{display:flex;align-items:center;gap:10px}.dept h3 .sp{flex:1}
.lvl{display:grid;grid-template-columns:28px 1.1fr .7fr 1fr 1fr 56px auto;gap:8px;align-items:center;padding:8px 0;border-bottom:1px solid var(--line)}.lvl:last-child{border:0}.lvl .n{color:var(--muted);font-size:12px;font-weight:700}
.feed div{padding:7px 0;border-bottom:1px solid var(--line);font-size:14px}.feed div:last-child{border:0}.feed small{color:var(--muted);margin-right:8px}
.qa{padding:8px 0;border-bottom:1px solid var(--line)}.qa:last-child{border:0}.qa b{display:block;color:var(--muted);font-size:12.5px;text-transform:uppercase;letter-spacing:.4px}.qa p{margin:2px 0 0;white-space:pre-wrap}
details summary{cursor:pointer;font-weight:600;padding:6px 0}
.av{width:32px;height:32px;border-radius:50%;vertical-align:middle;margin-right:8px;background:var(--panel2)}
.mnav{display:none;gap:6px;overflow-x:auto;padding:10px 14px;background:rgba(11,15,20,.7);backdrop-filter:blur(12px);border-bottom:1px solid var(--line);position:sticky;top:57px;z-index:15;scrollbar-width:none}.mnav::-webkit-scrollbar{display:none}.mnav a{white-space:nowrap;padding:7px 12px;border-radius:999px;color:var(--muted);background:var(--panel2);border:1px solid var(--line);font-size:13.5px;font-weight:500}.mnav a.on{color:#fff;background:linear-gradient(135deg,var(--accent),var(--accent2));border-color:transparent}
@media(max-width:860px){.row,.row3{grid-template-columns:1fr}.side{display:none}main{padding:18px 16px 60px}.mnav{display:flex!important}.top .user span.name{display:none}h1{font-size:22px}.lvl{grid-template-columns:24px 1fr 1fr;grid-auto-rows:auto}.lvl .hide{display:none}table{display:block;overflow-x:auto}.msgs{grid-template-columns:1fr}}
@media(prefers-reduced-motion:reduce){*{transition:none!important}}
`;


const EXTRA = `
.prev{background:#313338;border-radius:12px;padding:16px 18px;border-left:4px solid var(--pc,#9b6bff);font-family:Inter,system-ui,sans-serif;color:#dbdee1}.prev h3{color:#f2f3f5;margin:0 0 6px;font-size:18px}.prev h4{color:#f2f3f5;margin:14px 0 4px;font-size:15px}.prev .l{margin:2px 0;font-size:14.5px}.prev .c{background:rgba(88,101,242,.3);color:#c9cdfb;border-radius:3px;padding:0 3px;font-weight:500}.prev hr{border:0;border-top:1px solid #3f4147;margin:10px 0}.prev .ft{color:#949ba4;font-size:12px}
.catbox{border:1px solid var(--line);border-radius:12px;padding:14px 16px;margin-bottom:14px;background:rgba(0,0,0,.15)}.catbox .h{display:flex;gap:10px;align-items:center;flex-wrap:wrap;margin-bottom:8px}.catbox .h input[type=text]{max-width:280px}
.chrow{display:grid;grid-template-columns:200px 1fr auto;gap:10px;align-items:center;padding:7px 0;border-top:1px solid var(--line)}.chrow .n{font-weight:600;word-break:break-all}.chrow .n small{display:block;color:var(--muted);font-weight:400;font-size:12px}.chrow label{margin:0;text-transform:none;font-size:13px;display:flex;gap:6px;align-items:center;white-space:nowrap}
.sw{display:inline-block;width:14px;height:14px;border-radius:4px;vertical-align:middle;border:1px solid var(--line2)}
@media(max-width:860px){.chrow{grid-template-columns:1fr}}
`;
function layout({ title, session, guild, body }) {
  return `<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${esc(title)} — ChannelMap</title><style>${CSS}${EXTRA}</style></head><body>
<div class="top"><a class="brand" href="/dashboard">🗺️ ChannelMap</a>${guild ? `<span style="color:var(--muted)">· ${esc(guild.name)}</span>` : ''}<span class="sp"></span>${session ? `<span class="user">${session.user.avatar ? `<img src="${esc(session.user.avatar)}" alt="">` : ''}<span class="name">${esc(session.user.username)}</span><a href="/auth/logout" title="Log out">⏻</a></span>` : ''}</div>
<div class="wrap"><main style="max-width:1180px;margin:0 auto">${body}</main></div></body></html>`;
}
const flash = (q) => (q?.ok ? `<div class="ok">✅ ${esc(q.ok)}</div>` : q?.err ? `<div class="err">❌ ${esc(q.err)}</div>` : '');
const csrf = (s) => `<input type="hidden" name="_csrf" value="${esc(s.csrf)}">`;
const check = (name, on, label, hint) => `<div class="tog"><input type="checkbox" id="${name}" name="${name}" ${on ? 'checked' : ''}><label for="${name}" style="margin:0;text-transform:none;font-size:15px;color:var(--fg);font-weight:500">${label}${hint ? `<small>${hint}</small>` : ''}</label></div>`;
const when = (iso) => (iso ? new Date(iso).toLocaleString('en-GB', { dateStyle: 'medium', timeStyle: 'short', timeZone: 'UTC' }) + ' UTC' : 'never');
const hex = (n) => '#' + Number(n || 0).toString(16).padStart(6, '0');
const btnForm = (session, action, label, cls = 'sec', extra = '', confirm = '') => `<form method="post" class="inline" ${confirm ? `onsubmit="return confirm('${esc(confirm)}')"` : ''}>${csrf(session)}<input type="hidden" name="action" value="${action}">${extra}<button class="sm ${cls}">${label}</button></form>`;

module.exports = {
  esc,
  landing: ({ botName, avatar }) => layout({ title: 'Welcome', body: `<div class="center hero">${avatar ? `<img src="${esc(avatar)}" alt="">` : ''}<h1>${esc(botName)}</h1><p class="sub">A live <b>Channel Roadmap</b> for your server: every category and channel with its description, in one card that updates itself.</p><a class="btn" href="/auth/login">Login with Discord</a><p class="sub" style="margin-top:18px;font-size:13px">Manage Server required. <a href="/status">Bot status</a></p>
<div class="feat"><div><b>🗺️ Auto-generated</b>Reads your categories and channels</div><div><b>✏️ Editable</b>Descriptions, category names, hide anything</div><div><b>🔁 Two-way</b>Descriptions become channel topics and back</div><div><b>⏱️ Always fresh</b>Every 6 h and on every channel change</div></div></div>` }),
  error: (msg, session) => layout({ title: 'Error', session, body: `<div class="center"><h1>Something went wrong</h1><div class="err">${esc(msg)}</div><a class="btn sec" href="/dashboard">Back</a></div>` }),
  status: ({ session, ready, guilds, configured, uptime, ping, memoryMb, storage, errors }) => layout({ title: 'Status', session, body: `<h1>Bot status</h1><div class="grid"><div class="stat"><b style="color:${ready ? 'var(--green)' : 'var(--red)'}">${ready ? 'Online' : 'Offline'}</b><span>Discord</span></div><div class="stat"><b>${guilds}</b><span>Servers</span></div><div class="stat"><b>${configured}</b><span>Roadmaps</span></div><div class="stat"><b>${Math.floor(uptime / 86400)}d ${Math.floor((uptime % 86400) / 3600)}h ${Math.floor((uptime % 3600) / 60)}m</b><span>Uptime</span></div><div class="stat"><b>${ping ?? '–'} ms</b><span>Ping</span></div><div class="stat"><b>${memoryMb} MB</b><span>Memory</span></div><div class="stat"><b style="font-size:16px">${esc(storage)}</b><span>Storage</span></div></div>
<h2>Recent errors (${errors.length})</h2><div class="card">${errors.length ? errors.slice(0, 20).map((e) => `<div style="padding:6px 0;border-bottom:1px solid var(--line)"><small style="color:var(--muted)">${esc(e.at)}</small><br><code style="white-space:pre-wrap">${esc(e.text)}</code></div>`).join('') : '<p class="sub" style="margin:0">No errors since the last restart. 🎉</p>'}</div>` }),
  guilds: ({ session, guilds, invite }) => layout({ title: 'Your servers', session, body: `<h1>Your servers</h1><p class="sub">Servers where you have Manage Server.</p><div class="gl">${guilds.map((g) => g.inBot ? `<a href="/dashboard/${g.id}">${g.icon ? `<img src="${esc(g.icon)}" alt="">` : `<span class="ph">${esc(g.name[0] || '?')}</span>`}<span><b>${esc(g.name)}</b><small>${g.configured ? '🗺️ roadmap active' : 'not set up yet'} · ${g.channels} channels</small></span></a>` : `<a href="${esc(invite)}&guild_id=${g.id}" target="_blank">${g.icon ? `<img src="${esc(g.icon)}" alt="">` : `<span class="ph">${esc(g.name[0] || '?')}</span>`}<span><b>${esc(g.name)}</b><small>Bot not added — click to invite</small></span></a>`).join('') || '<div class="card">No servers found.</div>'}</div>` }),

  guild: ({ session, guild, g, q, textChannels, structure, preview, me }) => {
    const missing = [];
    if (me && !me.permissions.has('ManageChannels')) missing.push('Manage Channels (needed to write descriptions into channel topics)');
    const totalCh = structure.reduce((n, c) => n + c.channels.length, 0);
    return layout({ title: guild.name, session, guild, body: `<h1>${esc(guild.name)}</h1><p class="sub">${structure.length} categories · ${totalCh} channels · roadmap ${g.channelId ? `in <b>#${esc(textChannels.find((c) => c.id === g.channelId)?.name || g.channelId)}</b> (${g.messageIds.length} message${g.messageIds.length === 1 ? '' : 's'}) · last refresh ${when(g.lastRefresh)}` : '<b>not posted yet</b> — pick a channel below'}</p>${flash(q)}
${missing.length ? `<div class="err">⚠️ I am missing: ${missing.join(', ')}.</div>` : ''}
<div class="actions" style="margin-bottom:18px">${btnForm(session, 'refresh', '🔁 Refresh roadmap now', g.channelId ? '' : 'sec')}<a class="btn sm sec" href="#editor">✏️ Edit channels</a><a class="btn sm sec" href="#preview">👀 Preview</a></div>
<div class="row" style="grid-template-columns:1fr 1fr;align-items:start">
<div><h2>Settings</h2><div class="card"><form method="post">${csrf(session)}<input type="hidden" name="action" value="settings">
<label>Roadmap channel</label><select name="channelId"><option value="">— not posted —</option>${textChannels.map((c) => `<option value="${c.id}" ${c.id === g.channelId ? 'selected' : ''}># ${esc(c.name)}</option>`).join('')}</select>
<label>Title</label><input type="text" name="title" value="${esc(g.title)}" maxlength="100">
<label>Intro text (Markdown)</label><textarea name="intro" maxlength="1500">${esc(g.intro)}</textarea>
<label>Footer (empty = none)</label><input type="text" name="footer" value="${esc(g.footer)}" maxlength="200">
<div class="row"><div><label>Accent colour</label><input type="text" name="color" value="${hex(g.color)}" pattern="#?[0-9a-fA-F]{6}" style="font-family:monospace"></div><div><label>Auto-refresh every (hours)</label><input type="number" name="intervalHours" min="1" max="168" value="${g.intervalHours}"></div></div>
<div class="row"><div><label>Separator between categories</label><select name="separator">${['large', 'small', 'none'].map((s) => `<option value="${s}" ${g.separator === s ? 'selected' : ''}>${s}</option>`).join('')}</select></div><div><label>Name for channels without a category</label><input type="text" name="uncategorizedName" value="${esc(g.uncategorizedName)}" maxlength="80"></div></div>
${check('showVoice', g.showVoice, 'Include voice & stage channels')}${check('showEmptyCategories', g.showEmptyCategories, 'Show categories that have no visible channels')}
<button style="margin-top:12px">Save settings &amp; refresh</button></form></div>
<h2>Danger zone</h2><div class="card"><div class="actions">${btnForm(session, 'reset', 'Clear all custom descriptions / names / hidden flags', 'sec', '', 'Clear every override? Channel topics in Discord are not changed.')}${btnForm(session, 'remove', 'Stop posting the roadmap', 'danger', '', 'Stop updating the roadmap?')}</div></div></div>
<div id="preview"><h2>Preview</h2><div class="prev" style="--pc:${hex(g.color)}"><h3>${esc(g.title)}</h3>${g.intro ? `<div class="l">${esc(g.intro)}</div>` : ''}<hr>${preview.map((c) => `<h4>${esc(c.name)}</h4>${c.lines.map((l) => `<div class="l"><span class="c">${l.voice ? '🔊' : '#'} ${esc(l.name)}</span>${l.description ? ` - ${esc(l.description)}` : ''}</div>`).join('') || '<div class="l" style="color:#949ba4"><i>no channels</i></div>'}`).join('<hr>') || '<div class="l">Nothing to show.</div>'}${g.footer ? `<hr><div class="ft">${esc(g.footer)} · just now</div>` : ''}</div><p class="sub" style="margin-top:8px">Discord renders channel mentions with the right icon (text, voice, announcement, forum) and makes them clickable.</p></div></div>

<h2 id="editor">Channels</h2><p class="sub">Edit a description and save the category — it is written into the channel's topic in Discord too (voice channels have no topic, so their description lives only here). Rename a category for the roadmap without renaming it in Discord, or hide anything you don't want listed. Order always follows Discord.</p>
${structure.map((c) => `<div class="catbox" id="cat-${c.id}"><form method="post">${csrf(session)}<input type="hidden" name="action" value="category"><input type="hidden" name="id" value="${c.id}">
<div class="h"><span class="tag">${c.id === 'none' ? 'no category' : 'category'}</span><b>${esc(c.name)}</b><span style="color:var(--muted)">→ shown as</span><input type="text" name="name" value="${esc(c.id === 'none' ? (g.categories.none?.name || '') : (g.categories[c.id]?.name || ''))}" placeholder="${esc(c.name)}" maxlength="80"><label style="margin:0;text-transform:none;display:flex;gap:6px;align-items:center;font-size:13px"><input type="checkbox" name="hidden" ${c.hidden ? 'checked' : ''}> hide whole category</label><span class="sp" style="flex:1"></span><button class="sm">Save category</button></div>
${c.channels.map((x) => `<div class="chrow"><div class="n">${x.voice ? '🔊' : '#'} ${esc(x.name)}<small>${x.hasTopic ? (g.descriptions[x.id] !== undefined ? 'custom · synced to topic' : x.topic ? 'from channel topic' : 'no topic yet') : 'voice — stored here only'}</small></div><input type="text" name="desc_${x.id}" value="${esc(x.description)}" placeholder="Description shown after the channel name" maxlength="1024"><label><input type="checkbox" name="hide_${x.id}" ${x.hidden ? 'checked' : ''}> hide</label></div>`).join('') || '<p class="sub" style="margin:6px 0 0">No channels in this category.</p>'}
</form></div>`).join('')}` });
  },
};
